DROP TABLE IF EXISTS PEDIDO;

CREATE TABLE PEDIDO(
	COD_PEDIDO VARCHAR(15) NOT NULL, --Número do pedido
	COD_EMP VARCHAR(30) NOT NULL, --Código da empresa	
	VALOR NUMERIC(13,4) NOT NULL, --Valor do pedido
	TIP_PAG CHAR(2) NOT NULL, --Tipo de pagamento
	SIT_PAG CHAR(2) NOT NULL, --Situação do pagamento
	DT_PAG CHAR(8) NOT NULL, --Data do pagamento
	COD_AUT CHAR(10) NULL,
	NUM_ID CHAR(10) NULL,
	COMP_VEND CHAR(10) NULL,
	TIP_CARD CHAR(10) NULL,
	PRIMARY KEY (COD_PEDIDO)	
);

CREATE INDEX IDX_PEDIDO ON PEDIDO(COD_PEDIDO);

INSERT INTO PEDIDO (COD_PEDIDO, COD_EMP, VALOR, TIP_PAG, SIT_PAG, DT_PAG) VALUES('1', '1', 13, '01', '00', '22082017');

SELECT * FROM PEDIDO;
DELETE FROM PEDIDO;